[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configurações para rotas SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configuração para otimização de imagens Next.js
[build.environment]
  NEXT_USE_NETLIFY_EDGE = "true"
  NODE_VERSION = "18"
  # Desativa a geração estática para a página de busca que usa useSearchParams
  NEXT_DISABLE_PREBUNDLING = "1"
  NEXT_PUBLIC_NETLIFY_NEXT_PLUGIN_SKIP = "true" 